// <auto-generated />
namespace K_Systems.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderderdetailorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderderdetailorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201902100851565_orderderdetailorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
